# -*- coding: utf-8 -*-
"""medicalCost.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yjfIKgUYsIxPHTxIWYScAgO7QIVcl8qD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Data Analysis"""

medical=pd.read_csv('/insurance.csv')
medical.head()

"""information about the dataset"""

medical.info()

"""Target : to predict charges by categorizing data based on region

isnull() -> to check missing values
"""

medical.isnull()

medical.describe()    #gives statistical values(mean,median..)

"""data distribution"""

medical['region'].value_counts()

sns.set()
plt.figure(figsize=(6,6))
sns.countplot(x='region',data=medical)
plt.title('Region Distribution')
plt.show()

"""The data is almost same for all 4 .
Out of 4 regions , southeast has little higher (medical cost) data
"""

sns.set()
plt.figure(figsize=(6,6))
sns.countplot(x='sex',data=medical)
plt.title('Gender')
plt.show()

medical['sex'].value_counts()

"""This countplot throws an insight that male has slightly higher data than female ."""